lib: [
  "_build/install/default/lib/geopub/META"
  "_build/install/default/lib/geopub/dune-package"
  "_build/install/default/lib/geopub/opam"
]
share: [
  "_build/install/default/share/geopub/geopub.js"
  "_build/install/default/share/geopub/images/layers-2x.png" {"images/layers-2x.png"}
  "_build/install/default/share/geopub/images/layers.png" {"images/layers.png"}
  "_build/install/default/share/geopub/images/marker-icon-2x.png" {"images/marker-icon-2x.png"}
  "_build/install/default/share/geopub/images/marker-icon.png" {"images/marker-icon.png"}
  "_build/install/default/share/geopub/images/marker-shadow.png" {"images/marker-shadow.png"}
  "_build/install/default/share/geopub/index.html"
  "_build/install/default/share/geopub/leaflet.contextmenu.css"
  "_build/install/default/share/geopub/leaflet.css"
  "_build/install/default/share/geopub/sgraffito.svg"
  "_build/install/default/share/geopub/style.css"
]
doc: [
  "_build/install/default/doc/geopub/CHANGELOG.md"
  "_build/install/default/doc/geopub/README.md"
]
