#+TITLE: GeoPub

GeoPub is a content management system for [[https://miaengiadina.github.io/openengiadina/][open local knowledge]].

* Status

Currently in heavy development. Ideas on how to use an RDF graph as an underlying data model  and incorporate relational programming are being explored.

The intention is to mature the ideas into a working application.

** History

This is the third iteration of GeoPub. The initial two iterations were demonstrators:

- The initial demonstrator in JavaScript (a5c3785ed8d6a35868bc169f07e40e889087fd2e)
- The second demonstrator in ClojureScript (a5c3785ed8d6a35868bc169f07e40e889087fd2e)

* Developer quick start

See also the [[./docs/dev-notes.org][developer notes]].

** Prerequisites

- [[https://clojure.org/][Clojure]] (GeoPub is written in [[https://clojurescript.org/][ClojureScript]])
- [[https://nodejs.org/en/][Node.js (and npm)]] for getting JavaScript dependencies

** Install JavaScript dependencies

#+BEGIN_SRC sh
npm install
#+END_SRC

** Run development server

#+BEGIN_SRC sh
clj -A:shadow-cljs watch app
#+END_SRC

This will download any required ClojureScript dependencies, start a development
server. The application can now be accessed at [[http://localhost:9500/]].

** Building

#+BEGIN_SRC sh
clj -A:shadow-cljs release app
#+END_SRC

*** TODO copy public resources and create a complete build
